[build]
  base = "client/"
  command = "npm run build"
  publish = "dist/"

[[redirects]]
  from = "/api/*"
  to = "https://game-battleship-production.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "wss://game-battleship-production.up.railway.app/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://game-battleship-production.up.railway.app"